# Generated by Django 6.0.3 on 2026-04-02 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_face_embedding_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='face_embedding',
        ),
    ]
